In [1]:
import torch
import hatt

torch.manual_seed(10)

# Head Attention



In [2]:
device = 'cpu'
batch_size = 2
seq_len = 40

max_seq_len = 300
vocab_size = 100
emb_size = 128

head_size = 4

In [3]:
# на входе тензор (batch_size,seq_len,emb_size)
x = torch.rand(size=(batch_size,seq_len,emb_size),device=device)
x.shape, x.dtype

(torch.Size([2, 40, 128]), torch.float32)

In [4]:
head_attention = hatt.HeadAttention(emb_size=emb_size,head_size=head_size,max_seq_len=max_seq_len,device=device)

In [5]:
#  на выходе batch_size x seq_len x head_size
y = head_attention.forward(x)
y.shape, y.dtype

(torch.Size([2, 40, 4]), torch.float32)

In [6]:
# заготовка, чтоб посмотреть как работает softmax
t = torch.rand([2,4,3])
t.shape,t.dtype

(torch.Size([2, 4, 3]), torch.float32)

In [7]:
# сумма по каждой строке 1
torch.softmax(t,dim=-1)[0]

tensor([[0.3594, 0.3063, 0.3343],
        [0.3992, 0.3626, 0.2383],
        [0.2698, 0.4603, 0.2699],
        [0.3722, 0.2179, 0.4099]])

In [8]:
0.3594+ 0.3063+ 0.3343

1.0

In [9]:
# заготовка для маски (torch==1.0.1)
tril=torch.tril(torch.full((3,3),1.0))
tril

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [10]:
triu=torch.triu(torch.full((3,3),float('-inf')),diagonal=1)
triu

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

In [11]:
tril+triu

tensor([[1., -inf, -inf],
        [1., 1., -inf],
        [1., 1., 1.]])